# Este é o arquivo de configuração da Netlify.
# Salve-o como netlify.toml dentro da sua pasta "crypto 4".

[build]
  # Define o diretório base do projeto.
  # A Netlify vai "entrar" nesta pasta antes de fazer qualquer coisa.
  base = "crypto 4"
  
  # Define o diretório a ser publicado, relativo ao "base".
  # O ponto "." significa que o index.html está na própria pasta "crypto 4".
  publish = "."

[functions]
  # Define o diretório das funções, também relativo ao "base".
  directory = "netlify/functions"
